name: NeoFS System Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [opened, synchronize]

jobs:
  system_tests:
    uses: nspcc-dev/.github/.github/workflows/system-tests.yml@master
