name: Go tests

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_versions: [ '1.19', '1.20', '1.21' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ matrix.go_versions }}'

      - name: Restore Go modules from cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/pkg/mod
          key: deps-${{ hashFiles('go.sum') }}

      - name: Update Go modules
        run: make dep

      - name: Run tests
        run: make test
